trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Install node modules"
    npm install
    echo "<<< Installed node modules"
  displayName: Install Modules
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Compile vscode-plasticscm"
    npm run compile
    echo "<<< Compiled vscode-plasticscm"
  displayName: Compile extension
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Run tests"
    npm run test
    echo "<<< Tests ran"
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Publishing extension"
    npm run deploy -p $(VSCODE_MARKETPLACE_TOKEN)
    echo "<<< Extension published"
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))
